# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 394b32e650e02703e9224ef21c546b8a0b297fa950d41520adcffc30f4868ce863543f0c0d7868a2328bb614146f8b94ecd3abbb5b7620982d5216c5a92a1a00

test:
  secret_key_base: 64e2dac08dc951d141d3f8928a8a8081f20e29df67de3212ba7e7d07633470ffab2b2ff14e5d4cd24ef8fae588af032ccc0f5e0bb23a3ffa4a56d16009625a99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
